USE SCHEMA PUBLIC;

CREATE TABLE FD_GROUP_STG
  (
    FDGRP_CD   VARCHAR(6),
    FDGRP_DESC VARCHAR(62)
  ) ;

CREATE or replace FILE FORMAT USDA_FILE_FORMAT 
TYPE = 'CSV' 
COMPRESSION = 'AUTO' 
FIELD_DELIMITER = '^' 
RECORD_DELIMITER = '\n' 
SKIP_HEADER = 0 
FIELD_OPTIONALLY_ENCLOSED_BY = 'NONE' 
TRIM_SPACE = FALSE 
ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE 
ESCAPE = 'NONE' 
ESCAPE_UNENCLOSED_FIELD = '\134' 
DATE_FORMAT = 'AUTO' 
TIMESTAMP_FORMAT = 'AUTO' 
NULL_IF = ('\\N');

put file://C:\Users\kocha\Downloads\SR-Leg_ASC\FD_GROUP.txt @%FD_GROUP_STG ;

copy into FD_GROUP_STG from @%FD_GROUP_STG/FD_GROUP.txt.gz file_format = USDA_FILE_FORMAT;

CREATE TABLE FD_GROUP AS
SELECT REPLACE ( FDGRP_CD, '~', '') AS FDGRP_CD,
  REPLACE ( FDGRP_DESC, '~', '')    AS FDGRP_DESC
FROM FD_GROUP_STG;

COPY INTO WEIGHT_INGEST
FROM @MY_S3_BUCKET/load/
FILES = ( 'WEIGHT.txt')
FILE_FORMAT = ( FORMAT_NAME = USDA_FILE_FORMAT) ;

CREATE OR REPLACE TABLE WEIGHT (
    NDB_NO	VARCHAR(5)
    ,SEQ	VARCHAR(2)
    ,AMOUNT	NUMBER(6,3)
    ,MSRE_DESC	VARCHAR(84)
    ,GM_WGT	NUMBER(7,1)
    ,NUM_DATA_PTS	NUMBER(4,0)
    ,STD_DEV	NUMBER(7,3)
  );
  
--ETL to move WEIGHT data from WEIGHT_INGEST to WEIGHT
--LOAD STEP
INSERT INTO WEIGHT(
SELECT 
  //TRANSFORM STEP
    REPLACE(NDB_NO,'~') as NDB_NO
    ,REPLACE(SEQ,'~') as SEQ
    ,AMOUNT
    ,REPLACE(MSRE_DESC,'~') as MSRE_DESC
    ,GM_WGT
    ,NUM_DATA_PTS
    ,STD_DEV
--EXTRACT STEP 
FROM WEIGHT_INGEST);

CREATE OR REPLACE TABLE LANGDESC
  (
    FACTOR_CODE VARCHAR(5),
    DESCRIPTION VARCHAR(140)
  );

--Query external stage
SELECT $1, $2
FROM @MY_S3_BUCKET/load/LANGDESC.txt
(FILE_FORMAT => USDA_FILE_FORMAT);

COPY INTO LANGDESC ( FACTOR_CODE, DESCRIPTION )
FROM
  (
    SELECT REPLACE($1, '~'), 
      REPLACE ($2, '~')
    FROM @MY_S3_BUCKET/load/LANGDESC.txt
    (FILE_FORMAT => USDA_FILE_FORMAT)
  ) ;